In [1]:
import numpy as np
import pandas as pd

In [2]:
df =pd.read_csv("../dataset/cleaned_data.csv")

In [3]:
df.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,No,8,8,4,No
1,97,5.52,5.37,8,No,7,8,0,No
2,109,5.36,5.83,9,No,3,1,1,No
3,122,5.47,5.75,6,Yes,1,6,1,No
4,96,7.91,7.69,7,No,8,10,2,No

In [4]:
numeric_col=df.select_dtypes('number').columns.to_list()

In [5]:
catagorical_col=df.select_dtypes('object').columns.to_list()

In [6]:
# df['Placement_enco']=df['Placement'].map({"No":0,"Yes":1})
placement_encoded = df['Placement'].map({'Yes':1,"No":0})

In [7]:
# df['Intership_Ex_enco']=df['Internship_Experience'].map({"Yes":1,"No":0})
internship_encoded = df['Internship_Experience'].map({'Yes':1,"No":0})

In [8]:
df['Placement']=placement_encoded
df['Internship_Experience']=internship_encoded

### Numeric_To_BInary

In [9]:
numeric_correlation =pd.DataFrame()

In [10]:
from scipy.stats import pointbiserialr
correlation=[]
p_value=[]
for col in numeric_col:
    corr, pval = pointbiserialr(df[col], df['Placement'])
    correlation.append(corr)
    p_value.append(pval)
    print(f"Correlation of {col}:", corr, "p-value:", pval)

numeric_correlation['features']= numeric_col
numeric_correlation['correlation'] = correlation
numeric_correlation['p-value'] = p_value

Correlation of IQ: 0.283396936384599 p-value: 1.6446060885605778e-179
Correlation of Prev_Sem_Result: 0.31667285728562977 p-value: 4.998505987246395e-226
Correlation of CGPA: 0.3210761073977663 p-value: 1.1888221622900666e-232
Correlation of Academic_Performance: -0.016238326512902683 p-value: 0.10884887898068939
Correlation of Extra_Curricular_Score: -0.00857640458817026 p-value: 0.3971051996687866
Correlation of Communication_Skills: 0.3195765293452164 p-value: 2.205382115402972e-230
Correlation of Projects_Completed: 0.21454876682735843 p-value: 6.5220031859175334e-102

In [11]:
numeric_correlation

                 features  correlation        p-value
0                      IQ     0.283397  1.644606e-179
1         Prev_Sem_Result     0.316673  4.998506e-226
2                    CGPA     0.321076  1.188822e-232
3    Academic_Performance    -0.016238   1.088489e-01
4  Extra_Curricular_Score    -0.008576   3.971052e-01
5    Communication_Skills     0.319577  2.205382e-230
6      Projects_Completed     0.214549  6.522003e-102

In [12]:
from scipy.stats import chi2_contingency
import pandas as pd

table = pd.crosstab(df['Internship_Experience'], df['Placement'])
chi2, p, dof, ex = chi2_contingency(table)
print('f p < 0.05 => significant association between the two variables.')
print("Chi-square:", chi2, "p-value:", p)

f p < 0.05 => significant association between the two variables.
Chi-square: 0.8538525931724278 p-value: 0.35546473760918174

In [13]:
n = table.sum().sum()
cramers_v = np.sqrt(chi2 / (n * (min(table.shape) - 1)))
print("Cramér’s V:", cramers_v)

Cramér’s V: 0.009357651620416577

In [14]:
numeric_correlation['abs_correlation'] = np.abs(numeric_correlation['correlation'])

In [15]:
numeric_correlation

                 features  correlation        p-value  abs_correlation
0                      IQ     0.283397  1.644606e-179         0.283397
1         Prev_Sem_Result     0.316673  4.998506e-226         0.316673
2                    CGPA     0.321076  1.188822e-232         0.321076
3    Academic_Performance    -0.016238   1.088489e-01         0.016238
4  Extra_Curricular_Score    -0.008576   3.971052e-01         0.008576
5    Communication_Skills     0.319577  2.205382e-230         0.319577
6      Projects_Completed     0.214549  6.522003e-102         0.214549

In [16]:
numeric_correlation.sort_values('abs_correlation',ascending=False)

                 features  correlation        p-value  abs_correlation
2                    CGPA     0.321076  1.188822e-232         0.321076
5    Communication_Skills     0.319577  2.205382e-230         0.319577
1         Prev_Sem_Result     0.316673  4.998506e-226         0.316673
0                      IQ     0.283397  1.644606e-179         0.283397
6      Projects_Completed     0.214549  6.522003e-102         0.214549
3    Academic_Performance    -0.016238   1.088489e-01         0.016238
4  Extra_Curricular_Score    -0.008576   3.971052e-01         0.008576